import { ExternalLink, Github } from "lucide-react";
import { Button } from "@/components/ui/button";

const projects = [
  { category: "Computer Vision", title: "AI Video Attendance System", stack: ["Python", "OpenCV", "MTCNN", "Siamese Networks"], description: "Computer vision-based attendance system that processes classroom video, detects and recognizes faces, and automates attendance recording.", result: "Designed for low-resolution, real-world classroom video." },
  { category: "Generative AI", title: "Smart Cultural Storyteller", stack: ["Gemini 1.5 Flash", "Streamlit", "gTTS"], description: "Multimodal application that turns uploaded imagery into contextual cultural stories with downloadable text and audio narration.", result: "Combines vision-language understanding with accessible audio output." },
  { category: "Computer Vision", title: "Real-Time Face Mask Detection", stack: ["TensorFlow", "MobileNetV2", "OpenCV", "SSD"], description: "Real-time pipeline that detects faces from webcam video and classifies masked or unmasked subjects with confidence-labelled boxes.", result: "Uses batch inference across detected faces for real-time throughput." },
  { category: "Medical AI", title: "Skin Cancer Detection Application", stack: ["TensorFlow", "EfficientNetB3", "Flask", "Grad-CAM"], description: "Web application for multi-class dermoscopic image classification with interpretable Grad-CAM visual explanations.", result: "Evaluated at AUC 0.826 and sensitivity 0.916." },
  { category: "AI Navigation", title: "Intelligent Route Planning", stack: ["Python", "Reinforcement Learning", "Graph Algorithms", "GIS"], description: "AI and GIS-based route-planning prototype for navigation under spatial and environmental constraints.", result: "Benchmarks learning-based approaches against classical planning baselines." },
] as const;

const Projects = () => <section id="projects" className="lattice-surface border-b border-border bg-muted/20 px-6 py-24 lg:px-8"><div className="container mx-auto max-w-7xl">
  <div className="mb-14 grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="section-label">Featured projects · 01</p><h2 className="section-title">Practical AI systems, built end to end.</h2></div><p className="max-w-xl text-muted-foreground lg:justify-self-end">Selected work across computer vision, applied deep learning, generative AI, and intelligent navigation.</p></div>
  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-12">{projects.map((project, index) => <article key={project.title} className={`group relative overflow-hidden border border-border bg-background p-7 transition-all duration-300 hover:-translate-y-1 hover:border-primary/60 hover:bg-card ${index === 0 ? "md:col-span-2 lg:col-span-7 lg:row-span-2 lg:p-9" : "lg:col-span-5"}`}>
    <div className="absolute right-5 top-5 text-xs font-semibold text-muted-foreground/50">{String(index + 1).padStart(2, "0")}</div>
    <div className="flex h-full flex-col"><div><div className="mb-7 flex items-center gap-3"><span className="node-mark" /><p className="technical-label text-primary">{project.category}</p></div><h3 className={`${index === 0 ? "text-3xl md:text-4xl" : "text-xl md:text-2xl"} max-w-xl font-semibold leading-tight`}>{project.title}</h3><p className="mt-5 max-w-2xl text-sm leading-6 text-muted-foreground">{project.description}</p></div>
    <div className="mt-auto pt-8"><div className="flex flex-wrap gap-2">{project.stack.map((tech) => <span key={tech} className="border border-border bg-muted/30 px-2.5 py-1 text-xs text-muted-foreground">{tech}</span>)}</div><div className="mt-6 border-l border-primary/40 pl-4"><p className="technical-label">System outcome</p><p className="mt-2 text-sm text-muted-foreground">{project.result}</p></div><div className="mt-7 flex gap-2"><Button size="sm" variant="outline" onClick={() => window.open("https://github.com/pripat1008", "_blank")}><Github className="mr-2 h-4 w-4" />GitHub</Button>{index === 1 && <Button size="sm" variant="ghost" onClick={() => window.open("https://github.com/pripat1008", "_blank")}><ExternalLink className="mr-2 h-4 w-4" />View project</Button>}</div></div></div>
  </article>)}</div>
</div></section>;
export default Projects;