import { ExternalLink, Github } from "lucide-react";
import { Button } from "@/components/ui/button";

const projects = [
  { category: "Computer Vision", title: "AI Video Attendance System", stack: ["Python", "OpenCV", "MTCNN", "Siamese Networks"], description: "Computer vision-based attendance system that processes classroom video, detects and recognizes faces, and automates attendance recording.", result: "Designed for low-resolution, real-world classroom video." },
  { category: "Generative AI", title: "Smart Cultural Storyteller", stack: ["Gemini 1.5 Flash", "Streamlit", "gTTS"], description: "Multimodal application that turns uploaded imagery into contextual cultural stories with downloadable text and audio narration.", result: "Combines vision-language understanding with accessible audio output." },
  { category: "Computer Vision", title: "Real-Time Face Mask Detection", stack: ["TensorFlow", "MobileNetV2", "OpenCV", "SSD"], description: "Real-time pipeline that detects faces from webcam video and classifies masked or unmasked subjects with confidence-labelled boxes.", result: "Uses batch inference across detected faces for real-time throughput." },
  { category: "Medical AI", title: "Skin Cancer Detection Application", stack: ["TensorFlow", "EfficientNetB3", "Flask", "Grad-CAM"], description: "Web application for multi-class dermoscopic image classification with interpretable Grad-CAM visual explanations.", result: "Evaluated at AUC 0.826 and sensitivity 0.916." },
  { category: "AI Navigation", title: "Intelligent Route Planning", stack: ["Python", "Reinforcement Learning", "Graph Algorithms", "GIS"], description: "AI and GIS-based route-planning prototype for navigation under spatial and environmental constraints.", result: "Benchmarks learning-based approaches against classical planning baselines." },
] as const;

const Projects = () => <section id="projects" className="border-b border-border bg-muted/20 px-6 py-24 lg:px-8"><div className="container mx-auto max-w-6xl">
  <div className="mb-14 max-w-2xl"><p className="section-label">Featured projects</p><h2 className="section-title">Practical AI systems, built end to end.</h2><p className="mt-5 text-muted-foreground">Selected work across computer vision, applied deep learning, generative AI, and intelligent navigation.</p></div>
  <div className="grid gap-px border border-border bg-border md:grid-cols-2">{projects.map((project, index) => <article key={project.title} className={`bg-background p-7 transition-colors hover:bg-card ${index === 0 ? "md:col-span-2 md:grid md:grid-cols-[1fr_1fr] md:gap-12" : ""}`}><div><p className="text-xs font-semibold uppercase text-primary">{project.category}</p><h3 className="mt-5 text-xl font-semibold md:text-2xl">{project.title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{project.description}</p></div><div className={index === 0 ? "mt-7 md:mt-0" : ""}><div className="flex flex-wrap gap-2">{project.stack.map((tech) => <span key={tech} className="border border-border px-2.5 py-1 text-xs text-muted-foreground">{tech}</span>)}</div><p className="mt-5 text-sm text-muted-foreground">{project.result}</p><div className="mt-6 flex gap-2"><Button size="sm" variant="outline" onClick={() => window.open("https://github.com/pripat1008", "_blank")}><Github className="mr-2 h-4 w-4" />GitHub</Button>{index === 1 && <Button size="sm" variant="ghost" onClick={() => window.open("https://github.com/pripat1008", "_blank")}><ExternalLink className="mr-2 h-4 w-4" />View project</Button>}</div></div></article>)}</div>
</div></section>;
export default Projects;